from __future__ import annotations

import io
import json
import os
import tempfile
import threading
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from unittest.mock import patch

from qa_sentinel.cli import _print_results, main
from qa_sentinel.config import load_suite
from qa_sentinel.demo_api import create_demo_server
from qa_sentinel.models import (
    AssertionResult,
    AssertionSpec,
    HttpResponse,
    SuiteResult,
    TestCase,
    TestResult,
)
from qa_sentinel.reporting import build_report, render_html, render_junit_xml
from qa_sentinel.runner import SuiteRunner


class IntegrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.server = create_demo_server(port=0)
        cls.port = cls.server.server_port
        cls.thread = threading.Thread(target=cls.server.serve_forever, daemon=True)
        cls.thread.start()

    @classmethod
    def tearDownClass(cls) -> None:
        cls.server.shutdown()
        cls.server.server_close()
        cls.thread.join(timeout=2)

    def suite_document(self) -> dict[str, object]:
        base_url = f"http://127.0.0.1:{self.port}"
        return {
            "name": "Integration suite",
            "workers": 3,
            "variables": {"base_url": base_url, "api_token": "integration-secret"},
            "defaults": {"retries": 1, "retry_delay_seconds": 0},
            "tests": [
                {
                    "id": "health",
                    "name": "Health",
                    "url": "{{base_url}}/health?token={{api_token}}",
                    "assertions": [
                        {"type": "status", "equals": 200},
                        {"type": "json_path", "path": "status", "equals": "ok"},
                    ],
                },
                {
                    "id": "retry",
                    "name": "Retry",
                    "url": "{{base_url}}/unstable?key=integration&failures=1",
                    "assertions": [
                        {"type": "status", "equals": 200},
                        {"type": "json_path", "path": "attempt", "equals": 2},
                    ],
                },
                {
                    "id": "echo",
                    "name": "Echo",
                    "method": "POST",
                    "url": "{{base_url}}/echo",
                    "json": {"value": 9},
                    "assertions": [
                        {"type": "status", "equals": 201},
                        {"type": "json_path", "path": "received.value", "equals": 9},
                    ],
                },
            ],
        }

    def write_suite(self, directory: Path, document: dict[str, object] | None = None) -> Path:
        path = directory / "suite.json"
        path.write_text(json.dumps(document or self.suite_document()), encoding="utf-8")
        return path

    def test_parallel_run_preserves_order_and_retries(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            suite = load_suite(self.write_suite(Path(directory)))
            result = SuiteRunner().run(suite)
        self.assertTrue(result.is_successful)
        self.assertEqual([test.case.case_id for test in result.tests], ["health", "retry", "echo"])
        self.assertEqual(result.tests[1].response.attempts, 2)

    def test_failed_assertion_sets_non_successful_suite(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            {
                "name": "Expected failure",
                "url": f"http://127.0.0.1:{self.port}/status/418",
                "assertions": [{"type": "status", "equals": 200}],
            }
        ]
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "suite.json"
            path.write_text(json.dumps(document), encoding="utf-8")
            result = SuiteRunner().run(load_suite(path))
        self.assertFalse(result.is_successful)
        self.assertEqual(result.failed, 1)

    def test_reports_are_redacted_and_html_is_standalone(self) -> None:
        document = self.suite_document()
        document["tests"] = [document["tests"][0]]  # type: ignore[index]
        with tempfile.TemporaryDirectory() as directory:
            suite = load_suite(self.write_suite(Path(directory), document))
            result = SuiteRunner().run(suite)
        report = build_report(result, suite.known_secrets)
        serialized = json.dumps(report)
        html = render_html(result, suite.known_secrets)
        self.assertNotIn("integration-secret", serialized)
        self.assertNotIn("integration-secret", html)
        self.assertIn("[REDACTED]", serialized)
        self.assertIn("<!doctype html>", html)
        self.assertIn("Generated by QA Sentinel", html)

    def test_resolved_environment_secret_is_redacted_in_every_report(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            {
                "name": "Secret echo",
                "method": "POST",
                "url": f"http://127.0.0.1:{self.port}/echo?token=${{QA_API_TOKEN}}",
                "json": {"value": "${QA_API_TOKEN}"},
                "assertions": [
                    {"type": "status", "equals": 201},
                    {
                        "type": "json_path",
                        "path": "received.value",
                        "equals": "different",
                    },
                ],
            }
        ]
        with tempfile.TemporaryDirectory() as directory, patch.dict(
            os.environ, {"QA_API_TOKEN": "resolved-env-secret"}
        ):
            suite = load_suite(self.write_suite(Path(directory), document))
            result = SuiteRunner().run(suite)
        outputs = (
            json.dumps(build_report(result, suite.known_secrets)),
            render_html(result, suite.known_secrets),
            render_junit_xml(result, suite.known_secrets),
        )
        for output in outputs:
            self.assertNotIn("resolved-env-secret", output)
            self.assertIn("[REDACTED]", output)

    def test_junit_report_is_redacted_and_marks_failures(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            document["tests"][0],  # type: ignore[index]
            {
                "name": "Expected failure",
                "url": f"http://127.0.0.1:{self.port}/status/418?token=integration-secret",
                "assertions": [{"type": "status", "equals": 200}],
            },
        ]
        with tempfile.TemporaryDirectory() as directory:
            suite = load_suite(self.write_suite(Path(directory), document))
            result = SuiteRunner().run(suite)
        report = render_junit_xml(result, suite.known_secrets)
        self.assertIn('<testsuite name="Integration suite" tests="2" failures="1"', report)
        self.assertIn("<failure", report)
        self.assertNotIn("integration-secret", report)
        self.assertIn("[REDACTED]", report)

    def test_junit_network_error_is_not_double_counted_as_failure(self) -> None:
        case = TestCase(
            case_id="network",
            name="Network",
            method="GET",
            url="https://example.test",
            headers={},
            body=None,
            timeout_seconds=1,
            retries=0,
            retry_delay_seconds=0,
            retry_on_status=(),
            retry_non_idempotent=False,
            assertions=(AssertionSpec("status", {"equals": 200}),),
        )
        response = HttpResponse(None, {}, b"", 1, 1, "connection refused")
        test = TestResult(
            case=case,
            passed=False,
            response=response,
            assertions=(
                AssertionResult("request", False, "connection refused"),
            ),
            started_at="2026-08-27T00:00:00+00:00",
            finished_at="2026-08-27T00:00:00+00:00",
        )
        result = SuiteResult(
            "Errors",
            (test,),
            "2026-08-27T00:00:00+00:00",
            "2026-08-27T00:00:00+00:00",
            1,
        )
        report = render_junit_xml(result)
        self.assertIn('tests="1" failures="0" errors="1"', report)

    def test_console_output_redacts_known_secrets(self) -> None:
        case = TestCase(
            case_id="secret",
            name="Check resolved-env-secret",
            method="GET",
            url="https://example.test",
            headers={},
            body=None,
            timeout_seconds=1,
            retries=0,
            retry_delay_seconds=0,
            retry_on_status=(),
            retry_non_idempotent=False,
            assertions=(AssertionSpec("status", {"equals": 200}),),
        )
        response = HttpResponse(500, {}, b"resolved-env-secret", 1, 1)
        test = TestResult(
            case=case,
            passed=False,
            response=response,
            assertions=(
                AssertionResult(
                    "status",
                    False,
                    "upstream returned resolved-env-secret",
                    200,
                    500,
                ),
            ),
            started_at="2026-08-27T00:00:00+00:00",
            finished_at="2026-08-27T00:00:00+00:00",
        )
        result = SuiteResult(
            "Secret resolved-env-secret",
            (test,),
            "2026-08-27T00:00:00+00:00",
            "2026-08-27T00:00:00+00:00",
            1,
        )
        output = io.StringIO()
        with redirect_stdout(output):
            _print_results(result, known_secrets=("resolved-env-secret",))
        self.assertNotIn("resolved-env-secret", output.getvalue())
        self.assertIn("[REDACTED]", output.getvalue())

    def test_cli_writes_both_reports(self) -> None:
        document = self.suite_document()
        document["tests"] = [document["tests"][0], document["tests"][2]]  # type: ignore[index]
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            suite_path = root / "suite.json"
            suite_path.write_text(json.dumps(document), encoding="utf-8")
            html_path = root / "report.html"
            json_path = root / "report.json"
            junit_path = root / "report.xml"
            exit_code = main(
                [
                    "run",
                    str(suite_path),
                    "--html",
                    str(html_path),
                    "--json",
                    str(json_path),
                    "--junit",
                    str(junit_path),
                    "--quiet",
                ]
            )
            self.assertEqual(exit_code, 0)
            self.assertTrue(html_path.exists())
            self.assertTrue(json_path.exists())
            self.assertTrue(junit_path.exists())
            self.assertEqual(json.loads(json_path.read_text())["summary"]["passed"], 2)
            self.assertIn("<testsuite", junit_path.read_text())

    def test_validate_command_checks_config_without_network_requests(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            {
                "name": "No request",
                "url": "https://unreachable.invalid/health",
                "assertions": [{"type": "status", "equals": 200}],
            }
        ]
        with tempfile.TemporaryDirectory() as directory:
            suite_path = self.write_suite(Path(directory), document)
            output = io.StringIO()
            with redirect_stdout(output):
                exit_code = main(["validate", str(suite_path)])
        self.assertEqual(exit_code, 0)
        self.assertIn("Valid suite", output.getvalue())

    def test_validate_command_returns_two_for_config_errors(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            {
                "name": "Invalid assertion",
                "url": f"http://127.0.0.1:{self.port}/health",
                "assertions": [{"type": "status", "equals": "200"}],
            }
        ]
        with tempfile.TemporaryDirectory() as directory:
            suite_path = self.write_suite(Path(directory), document)
            error = io.StringIO()
            with redirect_stderr(error):
                exit_code = main(["validate", str(suite_path)])
        self.assertEqual(exit_code, 2)
        self.assertIn("HTTP integers", error.getvalue())


if __name__ == "__main__":
    unittest.main()
