from __future__ import annotations

import io
import json
import os
import tempfile
import threading
import unittest
from contextlib import redirect_stderr, redirect_stdout
from dataclasses import replace
from pathlib import Path
from unittest.mock import patch

from qa_sentinel.cli import _print_results, main
from qa_sentinel.config import load_suite
from qa_sentinel.demo_api import create_demo_server
from examples.order_server import create_order_server
from qa_sentinel.models import (
    AssertionResult,
    AssertionSpec,
    HttpResponse,
    SuiteResult,
    TestCase,
    TestResult,
)
from qa_sentinel.reporting import build_report, render_html, render_junit_xml
from qa_sentinel.runner import SuiteRunner


class IntegrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.server = create_demo_server(port=0)
        cls.port = cls.server.server_port
        cls.thread = threading.Thread(target=cls.server.serve_forever, daemon=True)
        cls.thread.start()

    @classmethod
    def tearDownClass(cls) -> None:
        cls.server.shutdown()
        cls.server.server_close()
        cls.thread.join(timeout=2)

    def suite_document(self) -> dict[str, object]:
        base_url = f"http://127.0.0.1:{self.port}"
        return {
            "name": "Integration suite",
            "workers": 3,
            "variables": {"base_url": base_url, "api_token": "integration-secret"},
            "defaults": {"retries": 1, "retry_delay_seconds": 0},
            "tests": [
                {
                    "id": "health",
                    "name": "Health",
                    "url": "{{base_url}}/health?token={{api_token}}",
                    "assertions": [
                        {"type": "status", "equals": 200},
                        {"type": "json_path", "path": "status", "equals": "ok"},
                    ],
                },
                {
                    "id": "retry",
                    "name": "Retry",
                    "url": "{{base_url}}/unstable?key=integration&failures=1",
                    "assertions": [
                        {"type": "status", "equals": 200},
                        {"type": "json_path", "path": "attempt", "equals": 2},
                    ],
                },
                {
                    "id": "echo",
                    "name": "Echo",
                    "method": "POST",
                    "url": "{{base_url}}/echo",
                    "json": {"value": 9},
                    "assertions": [
                        {"type": "status", "equals": 201},
                        {"type": "json_path", "path": "received.value", "equals": 9},
                    ],
                },
            ],
        }

    def write_suite(self, directory: Path, document: dict[str, object] | None = None) -> Path:
        path = directory / "suite.json"
        path.write_text(json.dumps(document or self.suite_document()), encoding="utf-8")
        return path

    def test_parallel_run_preserves_order_and_retries(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            suite = load_suite(self.write_suite(Path(directory)))
            result = SuiteRunner().run(suite)
        self.assertTrue(result.is_successful)
        self.assertEqual([test.case.case_id for test in result.tests], ["health", "retry", "echo"])
        self.assertEqual(result.tests[1].response.attempts, 2)

    def test_failed_assertion_sets_non_successful_suite(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            {
                "name": "Expected failure",
                "url": f"http://127.0.0.1:{self.port}/status/418",
                "assertions": [{"type": "status", "equals": 200}],
            }
        ]
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "suite.json"
            path.write_text(json.dumps(document), encoding="utf-8")
            result = SuiteRunner().run(load_suite(path))
        self.assertFalse(result.is_successful)
        self.assertEqual(result.failed, 1)

    def test_reports_are_redacted_and_html_is_standalone(self) -> None:
        document = self.suite_document()
        document["tests"] = [document["tests"][0]]  # type: ignore[index]
        with tempfile.TemporaryDirectory() as directory:
            suite = load_suite(self.write_suite(Path(directory), document))
            result = SuiteRunner().run(suite)
        report = build_report(result, suite.known_secrets)
        serialized = json.dumps(report)
        html = render_html(result, suite.known_secrets)
        self.assertNotIn("integration-secret", serialized)
        self.assertNotIn("integration-secret", html)
        self.assertIn("[REDACTED]", serialized)
        self.assertIn("<!doctype html>", html)
        self.assertIn("Generated by QA Sentinel", html)

    def test_environment_is_carried_into_reports(self) -> None:
        document = self.suite_document()
        document["environment"] = "staging"
        document["slow_threshold_ms"] = 250
        document["tests"] = [document["tests"][0]]  # type: ignore[index]
        with tempfile.TemporaryDirectory() as directory:
            suite = load_suite(self.write_suite(Path(directory), document))
            result = SuiteRunner().run(suite)
        report = build_report(result, suite.known_secrets)
        self.assertEqual(report["environment"], "staging")
        self.assertEqual(report["slow_threshold_ms"], 250.0)
        self.assertIn("Environment: staging", render_html(result, suite.known_secrets))
        self.assertIn("Number(reportData.slow_threshold_ms)", render_html(result, suite.known_secrets))
        self.assertIn('name="Integration suite [staging]"', render_junit_xml(result, suite.known_secrets))

    def test_html_report_explains_failed_assertions(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            {
                "name": "Expected failure",
                "url": f"http://127.0.0.1:{self.port}/status/418",
                "assertions": [{"type": "status", "equals": 200}],
            }
        ]
        with tempfile.TemporaryDirectory() as directory:
            suite = load_suite(self.write_suite(Path(directory), document))
            result = SuiteRunner().run(suite)
        html = render_html(result, suite.known_secrets)
        self.assertIn('class="test-card failed"', html)
        self.assertIn("Expected", html)
        self.assertIn("Actual", html)
        self.assertIn("<code>200</code>", html)
        self.assertIn("<code>418</code>", html)
        self.assertIn("aria-pressed=\"true\"", html)
        self.assertIn("No tests match this view", html)
        self.assertIn("Aug", html)
        self.assertIn('data-action="download-json"', html)
        self.assertIn('data-action="download-junit"', html)
        self.assertIn('data-attempts="1"', html)

    def test_failure_previews_are_bounded_content_aware_and_redacted(self) -> None:
        case = TestCase(
            case_id="preview",
            name="Preview",
            method="GET",
            url="https://example.test/preview",
            headers={},
            body=None,
            timeout_seconds=1,
            retries=0,
            retry_delay_seconds=0,
            retry_on_status=(),
            retry_non_idempotent=False,
            assertions=(AssertionSpec("status", {"equals": 200}),),
        )
        secret = "preview-secret"
        long_body = (json.dumps({"token": secret, "payload": "x" * 3000}) + "\n").encode()
        response_test = TestResult(
            case=case,
            passed=False,
            response=HttpResponse(
                500,
                {"Content-Type": "Application/JSON; charset=utf-8"},
                long_body,
                1,
                1,
            ),
            assertions=(AssertionResult("status", False, "response body was not healthy", 200, 500),),
            started_at="2026-08-27T00:00:00+00:00",
            finished_at="2026-08-27T00:00:00+00:00",
        )
        error_test = TestResult(
            case=case,
            passed=False,
            response=HttpResponse(
                None,
                {},
                b"",
                1,
                1,
                ("request failed at /Users/tester/project/" + secret + " " + "e" * 1800),
            ),
            assertions=(AssertionResult("request", False, "request failed", actual="error"),),
            started_at="2026-08-27T00:00:00+00:00",
            finished_at="2026-08-27T00:00:00+00:00",
        )
        binary_test = TestResult(
            case=case,
            passed=False,
            response=HttpResponse(
                500,
                {"Content-Type": "application/octet-stream"},
                b"\x00\x01\x02" * 20,
                1,
                1,
            ),
            assertions=(AssertionResult("status", False, "binary response was not healthy", 200, 500),),
            started_at="2026-08-27T00:00:00+00:00",
            finished_at="2026-08-27T00:00:00+00:00",
        )
        result = SuiteResult(
            "Preview safety",
            (response_test, error_test, binary_test),
            "2026-08-27T00:00:00+00:00",
            "2026-08-27T00:00:00+00:00",
            1,
        )

        report = build_report(result, (secret,))
        response_preview = report["tests"][0]["response_preview"]
        self.assertEqual(response_preview["content_type"], "application/json")
        self.assertTrue(response_preview["truncated"])
        self.assertLessEqual(len(response_preview["text"]), 2400)
        serialized = json.dumps(report)
        self.assertNotIn(secret, serialized)
        self.assertNotIn("/Users/tester", serialized)
        self.assertIn("[REDACTED]", response_preview["text"])
        self.assertLessEqual(len(report["tests"][1]["error"]), 1200)
        self.assertIn("[truncated]", report["tests"][1]["error"])
        self.assertEqual(
            report["tests"][2]["response_preview"]["text"],
            "[binary response body omitted]",
        )
        html = render_html(result, (secret,))
        self.assertIn("Response preview · application/json", html)
        self.assertIn("Response preview · application/octet-stream", html)

    def test_resolved_environment_secret_is_redacted_in_every_report(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            {
                "name": "Secret echo",
                "method": "POST",
                "url": f"http://127.0.0.1:{self.port}/echo?token=${{QA_API_TOKEN}}",
                "json": {"value": "${QA_API_TOKEN}"},
                "assertions": [
                    {"type": "status", "equals": 201},
                    {
                        "type": "json_path",
                        "path": "received.value",
                        "equals": "different",
                    },
                ],
            }
        ]
        with tempfile.TemporaryDirectory() as directory, patch.dict(
            os.environ, {"QA_API_TOKEN": "resolved-env-secret"}
        ):
            suite = load_suite(self.write_suite(Path(directory), document))
            result = SuiteRunner().run(suite)
        outputs = (
            json.dumps(build_report(result, suite.known_secrets)),
            render_html(result, suite.known_secrets),
            render_junit_xml(result, suite.known_secrets),
        )
        for output in outputs:
            self.assertNotIn("resolved-env-secret", output)
            self.assertIn("[REDACTED]", output)

    def test_junit_report_is_redacted_and_marks_failures(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            document["tests"][0],  # type: ignore[index]
            {
                "name": "Expected failure",
                "url": f"http://127.0.0.1:{self.port}/status/418?token=integration-secret",
                "assertions": [{"type": "status", "equals": 200}],
            },
        ]
        with tempfile.TemporaryDirectory() as directory:
            suite = load_suite(self.write_suite(Path(directory), document))
            result = SuiteRunner().run(suite)
        report = render_junit_xml(result, suite.known_secrets)
        self.assertIn('<testsuite name="Integration suite" tests="2" failures="1"', report)
        self.assertIn("<failure", report)
        self.assertNotIn("integration-secret", report)
        self.assertIn("[REDACTED]", report)

    def test_junit_network_error_is_not_double_counted_as_failure(self) -> None:
        case = TestCase(
            case_id="network",
            name="Network",
            method="GET",
            url="https://example.test",
            headers={},
            body=None,
            timeout_seconds=1,
            retries=0,
            retry_delay_seconds=0,
            retry_on_status=(),
            retry_non_idempotent=False,
            assertions=(AssertionSpec("status", {"equals": 200}),),
        )
        response = HttpResponse(None, {}, b"", 1, 1, "connection refused")
        test = TestResult(
            case=case,
            passed=False,
            response=response,
            assertions=(
                AssertionResult("request", False, "connection refused"),
            ),
            started_at="2026-08-27T00:00:00+00:00",
            finished_at="2026-08-27T00:00:00+00:00",
        )
        result = SuiteResult(
            "Errors",
            (test,),
            "2026-08-27T00:00:00+00:00",
            "2026-08-27T00:00:00+00:00",
            1,
        )
        report = render_junit_xml(result)
        self.assertIn('tests="1" failures="0" errors="1"', report)

    def test_console_output_redacts_known_secrets(self) -> None:
        case = TestCase(
            case_id="secret",
            name="Check resolved-env-secret",
            method="GET",
            url="https://example.test",
            headers={},
            body=None,
            timeout_seconds=1,
            retries=0,
            retry_delay_seconds=0,
            retry_on_status=(),
            retry_non_idempotent=False,
            assertions=(AssertionSpec("status", {"equals": 200}),),
        )
        response = HttpResponse(500, {}, b"resolved-env-secret", 1, 1)
        test = TestResult(
            case=case,
            passed=False,
            response=response,
            assertions=(
                AssertionResult(
                    "status",
                    False,
                    "upstream returned resolved-env-secret",
                    200,
                    500,
                ),
            ),
            started_at="2026-08-27T00:00:00+00:00",
            finished_at="2026-08-27T00:00:00+00:00",
        )
        result = SuiteResult(
            "Secret resolved-env-secret",
            (test,),
            "2026-08-27T00:00:00+00:00",
            "2026-08-27T00:00:00+00:00",
            1,
        )
        output = io.StringIO()
        with redirect_stdout(output):
            _print_results(result, known_secrets=("resolved-env-secret",))
        self.assertNotIn("resolved-env-secret", output.getvalue())
        self.assertIn("[REDACTED]", output.getvalue())

    def test_console_output_includes_expected_and_actual_values(self) -> None:
        case = TestCase(
            case_id="diagnostic",
            name="Diagnostic",
            method="GET",
            url="https://example.test",
            headers={},
            body=None,
            timeout_seconds=1,
            retries=0,
            retry_delay_seconds=0,
            retry_on_status=(),
            retry_non_idempotent=False,
            assertions=(AssertionSpec("status", {"equals": 200}),),
        )
        test = TestResult(
            case=case,
            passed=False,
            response=HttpResponse(418, {}, b"", 1, 1),
            assertions=(AssertionResult("status", False, "status did not match", 200, 418),),
            started_at="2026-08-27T00:00:00+00:00",
            finished_at="2026-08-27T00:00:00+00:00",
        )
        result = SuiteResult(
            "Diagnostics",
            (test,),
            "2026-08-27T00:00:00+00:00",
            "2026-08-27T00:00:00+00:00",
            1,
        )
        output = io.StringIO()
        with redirect_stdout(output):
            _print_results(result)
        self.assertIn("expected=200 actual=418", output.getvalue())

    def test_cli_writes_both_reports(self) -> None:
        document = self.suite_document()
        document["tests"] = [document["tests"][0], document["tests"][2]]  # type: ignore[index]
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            suite_path = root / "suite.json"
            suite_path.write_text(json.dumps(document), encoding="utf-8")
            html_path = root / "report.html"
            json_path = root / "report.json"
            junit_path = root / "report.xml"
            exit_code = main(
                [
                    "run",
                    str(suite_path),
                    "--html",
                    str(html_path),
                    "--json",
                    str(json_path),
                    "--junit",
                    str(junit_path),
                    "--quiet",
                ]
            )
            self.assertEqual(exit_code, 0)
            self.assertTrue(html_path.exists())
            self.assertTrue(json_path.exists())
            self.assertTrue(junit_path.exists())
            self.assertEqual(json.loads(json_path.read_text())["summary"]["passed"], 2)
            self.assertIn("<testsuite", junit_path.read_text())

    def test_cli_tag_filters_use_or_semantics_and_apply_excludes(self) -> None:
        document = self.suite_document()
        document["tests"][0]["tags"] = ["smoke", "contract"]  # type: ignore[index]
        document["tests"][1]["tags"] = ["resilience"]  # type: ignore[index]
        document["tests"][2]["tags"] = ["write", "destructive"]  # type: ignore[index]
        document["tests"][1]["url"] = document["tests"][1]["url"].replace(  # type: ignore[index]
            "key=integration", "key=tag-filter"
        )
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            suite_path = self.write_suite(root, document)
            report_path = root / "tagged.json"
            output = io.StringIO()
            with redirect_stdout(output):
                exit_code = main([
                    "run", str(suite_path), "--tag", "smoke", "--tag", "resilience",
                    "--exclude-tag", "destructive", "--json", str(report_path), "--quiet",
                ])
            self.assertEqual(exit_code, 0)
            report = json.loads(report_path.read_text())
            self.assertEqual([test["id"] for test in report["tests"]], ["health", "retry"])

            error = io.StringIO()
            with redirect_stderr(error):
                no_match = main(["run", str(suite_path), "--tag", "does-not-exist", "--json", str(root / "none.json")])
            self.assertEqual(no_match, 2)
            self.assertIn("matched zero tests", error.getvalue())

    def test_validate_command_checks_config_without_network_requests(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            {
                "name": "No request",
                "url": "https://unreachable.invalid/health",
                "assertions": [{"type": "status", "equals": 200}],
            }
        ]
        with tempfile.TemporaryDirectory() as directory:
            suite_path = self.write_suite(Path(directory), document)
            output = io.StringIO()
            with redirect_stdout(output):
                exit_code = main(["validate", str(suite_path)])
        self.assertEqual(exit_code, 0)
        self.assertIn("Valid suite", output.getvalue())

    def test_cli_environment_override_is_visible_during_validation(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            suite_path = self.write_suite(Path(directory), self.suite_document())
            output = io.StringIO()
            with redirect_stdout(output):
                exit_code = main(["validate", str(suite_path), "--environment", "ci"])
        self.assertEqual(exit_code, 0)
        self.assertIn("[ci]", output.getvalue())

    def test_validate_command_returns_two_for_config_errors(self) -> None:
        document = self.suite_document()
        document["tests"] = [
            {
                "name": "Invalid assertion",
                "url": f"http://127.0.0.1:{self.port}/health",
                "assertions": [{"type": "status", "equals": "200"}],
            }
        ]
        with tempfile.TemporaryDirectory() as directory:
            suite_path = self.write_suite(Path(directory), document)
            error = io.StringIO()
            with redirect_stderr(error):
                exit_code = main(["validate", str(suite_path)])
        self.assertEqual(exit_code, 2)
        self.assertIn("HTTP integers", error.getvalue())


class OrderWorkflowIntegrationTests(unittest.TestCase):
    def test_order_demo_rejects_non_loopback_bind_address(self) -> None:
        with self.assertRaisesRegex(ValueError, "only binds to loopback"):
            create_order_server(host="0.0.0.0", port=0)

    @classmethod
    def setUpClass(cls) -> None:
        cls.server = create_order_server(port=0)
        cls.port = cls.server.server_port
        cls.thread = threading.Thread(target=cls.server.serve_forever, daemon=True)
        cls.thread.start()

    @classmethod
    def tearDownClass(cls) -> None:
        cls.server.shutdown()
        cls.server.server_close()
        cls.thread.join(timeout=2)

    def setUp(self) -> None:
        with self.server.state_lock:  # type: ignore[attr-defined]
            self.server.orders.clear()  # type: ignore[attr-defined]
            self.server.next_order_id = 1001  # type: ignore[attr-defined]

    def suite(self, name: str) -> object:
        path = Path(__file__).parents[1] / "examples" / "order-workflow" / name
        return load_suite(path, {"base_url": f"http://127.0.0.1:{self.port}"})

    def test_order_lifecycle_success_cleans_up_state(self) -> None:
        suite = self.suite("order-workflow.json")
        result = SuiteRunner().run(suite)

        self.assertTrue(result.is_successful)
        self.assertEqual(result.total, 7)
        self.assertEqual(result.passed, 7)
        self.assertEqual([item.case.case_id for item in result.tests], [
            "login", "create", "read", "update", "verify", "audit", "cleanup"
        ])
        self.assertEqual(len(self.server.orders), 0)  # type: ignore[attr-defined]
        serialized = json.dumps(build_report(result, suite.known_secrets))
        self.assertNotIn("order-demo-access-token", serialized)

    def test_intentional_assertion_failure_blocks_audit_but_runs_cleanup(self) -> None:
        suite = self.suite("failure-workflow.json")
        result = SuiteRunner().run(suite)

        self.assertFalse(result.is_successful)
        self.assertEqual(result.failed, 1)
        self.assertEqual(result.blocked, 1)
        self.assertEqual(result.passed, 5)
        self.assertEqual([item.case.case_id for item in result.tests if item.status == "blocked"], ["audit"])
        self.assertEqual(result.tests[-1].status, "passed")
        self.assertEqual(len(self.server.orders), 0)  # type: ignore[attr-defined]

    def test_transport_error_does_not_send_broken_cleanup_request(self) -> None:
        suite = self.suite("order-workflow.json")
        cases = list(suite.tests)
        create_index = next(index for index, case in enumerate(cases) if case.case_id == "create")
        cases[create_index] = replace(cases[create_index], url="http://127.0.0.1:1/orders")
        suite = replace(suite, tests=tuple(cases))

        result = SuiteRunner().run(suite)

        self.assertEqual(result.errors, 1)
        self.assertEqual(result.blocked, 5)
        self.assertEqual(len(self.server.orders), 0)  # type: ignore[attr-defined]
        self.assertEqual(result.tests[-1].status, "blocked")
        self.assertIn("capture", result.tests[-1].response.error or "")


if __name__ == "__main__":
    unittest.main()
